image:
  file: .gitpod.Dockerfile

workspaceLocation: "./rust-multiplayer-physics"

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Server
    init: |
      echo 'Building Server'
      cd ./server
      cargo run --release
    command: |
      echo 'Starting Server'
      cd ./server
      cargo watch -x 'run --release'

  - name: Static Server
    command: |
      gp ports await 6464
      echo 'Starting Static Server'
      cd ./client
      python -m http.server 6465
    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Server
    port: 6464-6465
    onOpen: open-preview
    visibility: public