image:
  file: .gitpod.Dockerfile

workspaceLocation: "./rust-multiplayer-physics"

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Test
    command: pwd
  - name: Static Server
    command: sh ./setup_scripts/start_static_frontend.sh
  - name: DB Server
    command: sh ./setup_scripts/start_server.sh
    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Static Site
    port: 80
    onOpen: open-preview
  - name: Server
    port: 6464
    onOpen: ignore